name: CI/CD

on:
  push:
    branches:
      - feature/testing
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '23.10.0'
          cache: 'npm'

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1.5.0
        with:
          version: latest

      - name: Verify Supabase CLI
        run: supabase --version

      - name: Verify Docker
        run: docker info

      - name: Init Supabase DB
        run: |
          supabase init --force
          supabase db start

      - name: Run Supabase Tests
        run: supabase test db --debug

      - name: Stop Supabase
        if: always()
        run: supabase stop --no-backup

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
